#ifndef ASTNODES_H
#define ASTNODES_H

#include "Assignment.h"
#include "Attribute.h"
#include "BinaryOperator.h"
#include "Block.h"
#include "Cast.h"
#include "Class.h"
#include "DeferStatement.h"
#include "LoopControl.h"
#include "Dispatch.h"
#include "Expression.h"
#include "FieldAccess.h"
#include "FormalParam.h"
#include "IfStatement.h"
#include "IntConstant.h"
#include "FloatConstant.h"
#include "LocalDefinition.h"
#include "Method.h"
#include "NewObject.h"
#include "NullConstant.h"
#include "Program.h"
#include "SpawnStatement.h"
#include "StaticDispatch.h"
#include "StringConstant.h"
#include "Substring.h"
#include "Slicevector.h"
#include "Symbol.h"
#include "ThrowStatement.h"
#include "TryStatement.h"
#include "UnaryOperator.h"
#include "WhileStatement.h"
#include "ForStatement.h"
#include "Return.h"

#endif /* ASTNODES_H */
