#!/usr/bin/env python3
"""make_keywords.py [--check]

Writes lib/keywords.cmm: the words the lexer treats as keywords, read from the
rules in catmint-lex/catmint.l, so the editor's highlighting cannot drift from
the language. A developer's tool; its output is committed.

With --check it writes nothing and exits 1 if the committed file is not what
the lexer now says -- test.sh runs that.

A keyword rule is a quoted word whose action returns a KW_ token, or `and` and
`or`, which the lexer returns as operators. A quoted word with any other action
is refused rather than guessed at: it is a new kind of word, and what the
editor should do with it is a decision for a person.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEXER = os.path.join(ROOT, "catmint-lex", "catmint.l")
OUTPUT = os.path.join(ROOT, "lib", "keywords.cmm")

RULE = re.compile(r'^"([A-Za-z_]+)"\s*\{(.*)\}\s*$')
KEYWORD_ACTION = re.compile(r"return\s+(KW_[A-Z_]+|OP_ANDALSO|OP_ORELSE)\s*;")


def keywords():
    words = []
    for number, line in enumerate(open(LEXER), 1):
        m = RULE.match(line.strip())
        if not m:
            continue
        word, action = m.groups()
        if not KEYWORD_ACTION.search(action):
            raise SystemExit("make_keywords: catmint.l:%d: the rule for \"%s\" "
                             "returns something that is not a keyword token: %s"
                             % (number, word, action.strip()))
        if word not in words:
            words.append(word)
    if len(words) < 30:
        raise SystemExit("make_keywords: found only %d keywords in %s; the "
                         "lexer's layout has changed" % (len(words), LEXER))
    return words


def render(words):
    out = []
    out.append("# Generated by tools/make_keywords.py from catmint-lex/catmint.l -- do not edit.")
    out.append("#")
    out.append("# The words the lexer treats as keywords, so that the editor colours exactly")
    out.append("# those. test.sh runs `make_keywords.py --check`, which fails if this file and")
    out.append("# the lexer disagree.")
    out.append("class Keywords")
    out.append("  # Every keyword, each with a space on both sides.")
    out.append("  static def String all:")
    out.append("    return \" \"")
    for w in words:
        out.append("      + \"%s \"" % w)
    out.append("  end")
    out.append("")
    out.append("  # 1 if word is a keyword, else 0.")
    out.append("  static def Int has(String word):")
    out.append("    if Keywords.all().indexOf(\" \" + word + \" \") >= 0 and word.len() > 0:")
    out.append("      return 1")
    out.append("    end")
    out.append("    return 0")
    out.append("  end")
    out.append("end")
    return "\n".join(out) + "\n"


def main():
    text = render(keywords())
    if "--check" in sys.argv[1:]:
        try:
            current = open(OUTPUT).read()
        except FileNotFoundError:
            current = None
        if current != text:
            raise SystemExit("make_keywords: lib/keywords.cmm is out of date with "
                             "catmint-lex/catmint.l; run tools/make_keywords.py")
        print("keywords match the lexer (%d)" % len(keywords()))
    else:
        with open(OUTPUT, "w") as f:
            f.write(text)


main()
