#!/usr/bin/env python3
"""make_font.py unscii-16.hex > lib/fontdata.cmm

The printable ASCII glyphs of Unscii (8 x 16 pixels each), as a catmint module.

Unscii is by Viznut, https://github.com/viznut/unscii, and is public domain /
CC0 -- except for the files derived from Unifont (unifont.hex, unscii-16-full.*),
which are GPL and which this does not touch: it reads unscii-16.hex only.

A developer's tool, run once; its output is committed and nothing at run time
reads a font file. The input is one line per glyph, `CODEPOINT:` and then 32 hex
digits, two for each of the sixteen rows, the leftmost pixel the high bit.
"""
import sys

FIRST, LAST = 32, 126


def main():
    glyphs = {}
    with open(sys.argv[1]) as f:
        for line in f:
            code, _, bits = line.strip().partition(":")
            if len(bits) == 32 and FIRST <= int(code, 16) <= LAST:
                glyphs[int(code, 16)] = bits.upper()
    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        raise SystemExit("make_font: no 8x16 glyph for %s" % missing)

    out = []
    out.append("# Generated by tools/make_font.py from Unscii -- do not edit.")
    out.append("#")
    out.append("# Unscii is by Viznut (https://github.com/viznut/unscii) and is public domain /")
    out.append("# CC0. These are its 95 printable ASCII glyphs, space (32) to ~ (126), 8 pixels")
    out.append("# wide and 16 high: sixteen rows each, two hex digits a row, the leftmost pixel")
    out.append("# the high bit. A glyph is 32 characters; lib/font.cmm turns them into pixels.")
    out.append("class FontData")
    out.append("  static def String hex:")
    out.append("    return \"\"")
    for code in range(FIRST, LAST + 1):
        shown = chr(code) if chr(code) not in '"\\' else "\\" + chr(code)
        out.append("      + \"%s\"   # %d %s" % (glyphs[code], code, shown if code != 32 else "space"))
    out.append("  end")
    out.append("end")
    sys.stdout.write("\n".join(out) + "\n")


main()
